apiVersion: "kubeflow.org/v1alpha3"
kind: Experiment
metadata:
  namespace: mb18lasy
  labels:
    controller-tools.k8s.io: "1.0"
  name: visum-example
spec:
  objective:
    type: maximize
    goal: 0.93
    objectiveMetricName: accuracy
  algorithm:
    algorithmName: random
  parallelTrialCount: 25
  maxTrialCount: {.maxTrials}
  maxFailedTrialCount: {.maxTrials}
  parameters:
    - name: --neighbors
      parameterType: int
      feasibleSpace:
        min: "2"
        max: "150"
    - name: --gamma
      parameterType: double
      feasibleSpace:
        min: "0.00001"
        max: "0.1"
    - name: --model
      parameterType: categorical
      feasibleSpace:
        list:
        - sklearn.svm.SVC
        - sklearn.neighbors.KNeighborsClassifier
        - sklearn.linear_model.LinearRegression
  trialTemplate:
    goTemplate:
        rawTemplate: |-
          apiVersion: batch/v1
          kind: Job
          metadata:
            name: {{.Trial}}
            namespace: {{.NameSpace}}
          spec:
            template:
              spec:
                containers:
                - name: {{.Trial}}
                  image: docker.io/mbu93/visum-pipeline-runner:latest
                  command:
                  - "python"
                  - "main.py"
                  - "preprocess"
                  - "--out"
                  - "/tmp"
                  - "&&"
                  - "python"
                  - "main.py"
                  - "tune"
                  - "--model"
                  - "sklearn.svm.SVC"
                  - "--out"
                  - "/tmp"
                  {{- with .HyperParameters}}
                  {{- range .}}
                  - "{{.Name}}={{.Value}}"
                  {{- end}}
                  {{- end}}
                  imagePullPolicy: Always
                restartPolicy: OnFailure
